//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przeliterowywacz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Przeliterowywacz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        public static string AboutCaption {
            get {
                return ResourceManager.GetString("AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program name: {0}
        ///Version: {1}
        ///Author: {2}
        ///{3}
        ///Modifying and selling this program is strictly prohibited.
        ///Special thanks to Mark Heath for NAudio library and 
        ///pfcode for lending the voice for the default speech bank..
        /// </summary>
        public static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Banki&quot; FOLDER NOT FOUND.
        /// </summary>
        public static string BanksFolderNotFound {
            get {
                return ResourceManager.GetString("BanksFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and white.
        /// </summary>
        public static string BlackAndWhite {
            get {
                return ResourceManager.GetString("BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ca {
            get {
                object obj = ResourceManager.GetObject("ca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot concatenate sound files that don&apos;t share the same format!.
        /// </summary>
        public static string CannotConcatenateDifferentFormatsException {
            get {
                return ResourceManager.GetString("CannotConcatenateDifferentFormatsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another language has just been selected. To see the changes, save current settings now and restart the application..
        /// </summary>
        public static string ChangedLanguageMessage {
            get {
                return ResourceManager.GetString("ChangedLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common settings.
        /// </summary>
        public static string CommonSettings {
            get {
                return ResourceManager.GetString("CommonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;default&gt;.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derive files from the default speech bank if such are missing in the selected one.
        /// </summary>
        public static string DeriveFromDefaultSpeechbank {
            get {
                return ResourceManager.GetString("DeriveFromDefaultSpeechbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable special and punctuation chars (e.g. comma, exclamation mark, asterisk etc.).
        /// </summary>
        public static string EnableSpecialChars {
            get {
                return ResourceManager.GetString("EnableSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed..
        /// </summary>
        public static string FailedStatus {
            get {
                return ResourceManager.GetString("FailedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound files (*.wav)|*.wav|All files|*.*.
        /// </summary>
        public static string FileTypes {
            get {
                return ResourceManager.GetString("FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to be read here.
        /// </summary>
        public static string FirstInput {
            get {
                return ResourceManager.GetString("FirstInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation aborted because the problem has occured with the following sound file: {0}{1}. Please make sure the file exists..
        /// </summary>
        public static string HaltedDueToFileMessage {
            get {
                return ResourceManager.GetString("HaltedDueToFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program busy. In order to do it, you need to wait for the end of the operation first..
        /// </summary>
        public static string IsBusyMessage {
            get {
                return ResourceManager.GetString("IsBusyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language: .
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAudio.dll file required for using the recording feature is missing in the program&apos;s directory. Please reinstall this software..
        /// </summary>
        public static string NAudioNotFoundMessage {
            get {
                return ResourceManager.GetString("NAudioNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to be recorded first..
        /// </summary>
        public static string NoTextToRecordMessage {
            get {
                return ResourceManager.GetString("NoTextToRecordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to be spelled first..
        /// </summary>
        public static string NoTextToSpellMessage {
            get {
                return ResourceManager.GetString("NoTextToSpellMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string OptionsButton {
            get {
                return ResourceManager.GetString("OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program options.
        /// </summary>
        public static string OptionsCaption {
            get {
                return ResourceManager.GetString("OptionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pl {
            get {
                object obj = ResourceManager.GetObject("pl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate: .
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all zero characters as the letter &apos;o&apos;.
        /// </summary>
        public static string ReadZeroAsOLetter {
            get {
                return ResourceManager.GetString("ReadZeroAsOLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPI5 error: .
        /// </summary>
        public static string SAPI5Error {
            get {
                return ResourceManager.GetString("SAPI5Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPI5 settings.
        /// </summary>
        public static string SAPI5Settings {
            get {
                return ResourceManager.GetString("SAPI5Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPI5 synthesis.
        /// </summary>
        public static string SAPI5Synthesis {
            get {
                return ResourceManager.GetString("SAPI5Synthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAPI5 voice: .
        /// </summary>
        public static string SAPI5Voice {
            get {
                return ResourceManager.GetString("SAPI5Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The voice &quot;{0}&quot; is unavailable, therefore program will read the text by means of the default speech synthesizer..
        /// </summary>
        public static string SAPI5VoiceMissingMessage {
            get {
                return ResourceManager.GetString("SAPI5VoiceMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SAPI5 voice called &quot;{0}&quot; has not been found, default setting has been restored..
        /// </summary>
        public static string SAPI5VoiceNotFoundMessage {
            get {
                return ResourceManager.GetString("SAPI5VoiceNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        public static string SavedStatus {
            get {
                return ResourceManager.GetString("SavedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save settings.
        /// </summary>
        public static string SaveSettingsButton {
            get {
                return ResourceManager.GetString("SaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech bank: .
        /// </summary>
        public static string Speechbank {
            get {
                return ResourceManager.GetString("Speechbank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The speech bank folder called &quot;{0}&quot; has not been found, default setting has been restored..
        /// </summary>
        public static string SpeechbankFolderNotFoundMessage {
            get {
                return ResourceManager.GetString("SpeechbankFolderNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech banks.
        /// </summary>
        public static string Speechbanks {
            get {
                return ResourceManager.GetString("Speechbanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech bank settings.
        /// </summary>
        public static string SpeechbankSettings {
            get {
                return ResourceManager.GetString("SpeechbankSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Spell.
        /// </summary>
        public static string SpellButton {
            get {
                return ResourceManager.GetString("SpellButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to do this operation because the previously called one is still in progress. In order to do it, you need to wait for its finish..
        /// </summary>
        public static string StillWorkingMessage {
            get {
                return ResourceManager.GetString("StillWorkingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_top.
        /// </summary>
        public static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input colour scheme: .
        /// </summary>
        public static string TextInputColorScheme {
            get {
                return ResourceManager.GetString("TextInputColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: .
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has not been saved successfully because one or more files required to play have not been found..
        /// </summary>
        public static string WAVEFilesMissingMessage {
            get {
                return ResourceManager.GetString("WAVEFilesMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.komputermania.pl.eu.org/.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Website.
        /// </summary>
        public static string WebsiteButton {
            get {
                return ResourceManager.GetString("WebsiteButton", resourceCulture);
            }
        }
    }
}
